# Site settings
 title: "JMAP"
 description: "This is JMAP. The framework is designed in collaborative way, based on Jekyll to generate maps from data. Created and distribute with MIT licence."

 collections:
  maps:
    output: true
    permalink: /:collection/:name


 email: mtempestini@gmail.com

#blog logo
 logo: "logo.jpg"
 float_logo: true # true, false (default)

# blog cover
 cover: "/assets/images/back.jpeg"

name: 'Matteo Tempestini'
author: 'Matteo Tempestini'
author_image: "logo.jpg"

 paginate:	5

 url: "https://iltempe.github.io" # the base hostname & protocol for your site
 baseurl: "/jmap"

#used to display twitter cards
 twitter_handle: '@il_tempe'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
 social:
  - icon:	twitter
    url:	https://twitter.com/il_tempe
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/iltempe/jmap
    desc:	Fork me on github
    share_url: https://github.com/iltempe/jmap
    share_title: JMAP
    share_link: https://github.com/iltempe/jmap

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

 plugins:
  - jemoji
  - jekyll-paginate
